// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKWdXwvbIYGiB5NYmCtxAsR-uxRXY8cQ',
    appId: '1:489896571281:web:478b766f34e828afd4ea30',
    messagingSenderId: '489896571281',
    projectId: 'graduation-project-c1589',
    authDomain: 'graduation-project-c1589.firebaseapp.com',
    storageBucket: 'graduation-project-c1589.appspot.com',
    measurementId: 'G-BC3590VD3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeVdDrWsP9GsTu6kNcnB4ZO14u71phNUM',
    appId: '1:489896571281:android:3c66b6b72693adb3d4ea30',
    messagingSenderId: '489896571281',
    projectId: 'graduation-project-c1589',
    storageBucket: 'graduation-project-c1589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-3laeSc7RtUOKpksm-nMw0AsxVKhbTM',
    appId: '1:489896571281:ios:4fbd705cb453cfc3d4ea30',
    messagingSenderId: '489896571281',
    projectId: 'graduation-project-c1589',
    storageBucket: 'graduation-project-c1589.appspot.com',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-3laeSc7RtUOKpksm-nMw0AsxVKhbTM',
    appId: '1:489896571281:ios:f629872d59bae0b9d4ea30',
    messagingSenderId: '489896571281',
    projectId: 'graduation-project-c1589',
    storageBucket: 'graduation-project-c1589.appspot.com',
    iosBundleId: 'com.example.graduation.RunnerTests',
  );
}
